site_name: Eclipse Dirigible Help
theme:
  name: mkdocs
  palette:
    scheme: default
  features:
    - navigation.tabs
markdown_extensions:
    - pymdownx.snippets
    - pymdownx.highlight:
        linenums: false
    - pymdownx.keys
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.tabbed