name: CI
on:
  push:
    branches: 
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site with squidfunk/mkdocs-material container
      run: |
        docker pull squidfunk/mkdocs-material
        docker run -v ${{ github.workspace }}/docs-api:/docs squidfunk/mkdocs-material build
        docker run -v ${{ github.workspace }}/docs-help:/docs squidfunk/mkdocs-material build
        docker run -v ${{ github.workspace }}/docs-samples:/docs squidfunk/mkdocs-material build
        mkdir api
        cp -a docs-api/site/. api/
        mkdir help
        cp -a docs-help/site/. api/
        mkdir samples
    - name: Git Commit and Push
    # You may pin to the exact commit or the version.
    # uses: github-actions-x/commit@3638e497fc2bda72d701660f4619cd0efaf0bcf3
      uses: github-actions-x/commit@v2.6
      with:
        github-token: ${{secrets.GH_TOKEN}}
        push-branch: gh-pages
        email: ${{secrets.GH_MAIL}}

#     # Override branch to push to
#     push-branch: # optional
#     # Specify commit message
#     commit-message: # optional, default is autocommit
#     # Force add files, useful for adding ignored files.
#     force-add: # optional, default is false
#     # Pull and rebase before commiting. Useful when using commit inside matrix.
#     rebase: # optional, default is false
#     # Specific files to add.
#     files: # optional, default is 
#     # Committer email. Default is ${name}@users.noreply.github.com
#     email: # optional, default is 
#     # Committer name. Default is name of the person or app that initiated the workflow.
#     name: # optional, default is 
#         pwd
#         ls
#         mkdir api
#         cp -a docs-api/site/. api/
#         mkdir help
#         cp -a docs-help/site/. api/
#         mkdir samples
#         cp -a docs-samples/site/. api/
#         rm -rf docs-api/
#         rm -rf docs-help/
#         rm -rf docs-samples/
#         pwd
#         ls
#         cd api
#         ls
#         cd ../help
#         ls
#         cd ../samples
#         ls
#         cd ..
#         ls
        
#docker run 
# -v ${{ github.workspace }}:/srv/jekyll
# -v ${{ github.workspace }}/_site:/srv/jekyll/_site
# jekyll/builder:latest 
# /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
