name: CI
on:
  push:
    branches: 
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site with squidfunk/mkdocs-material container
      run: |
        docker pull squidfunk/mkdocs-material
        docker run -v ${{ github.workspace }}/docs-api:/docs squidfunk/mkdocs-material build
        docker run -v ${{ github.workspace }}/docs-help:/docs squidfunk/mkdocs-material build
        docker run -v ${{ github.workspace }}/docs-samples:/docs squidfunk/mkdocs-material build
        mv docs-api/site api
        mv docs-help/site help
        mv docs-samples/site samples
        rm -rf docs-api
        rm -rf docs-help
        rm -rf docs-samples
        pwd
        ls
        cd api
        ls
        cd ../help
        ls
        cd ../samples
        ls
        cd ..
        ls
        
#docker run 
# -v ${{ github.workspace }}:/srv/jekyll
# -v ${{ github.workspace }}/_site:/srv/jekyll/_site
# jekyll/builder:latest 
# /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
